package com.syncshopper.domain.user;

public enum UserEventType {
    PRODUCT_DETAIL_VIEW,
    PRODUCT_CLICK,
    AFFILIATE_CLICK,
    WISHLIST_ADD,
    WISHLIST_REMOVE,
    PRODUCT_IGNORE,
    PRODUCT_SAVE,
    WEB_SEARCH_STARTED,
    WEB_SEARCH_COMPLETED,
    WEB_SEARCH_FAILED,
    SEARCH_RESULT_VIEWED,
    SEARCH_RESULT_CLICKED,
    AI_CANDIDATE_VERIFIED
}
